### ISSUE TITLE
Physical Architecture: FlexTrak STM32 Transceiver Modelling (Downlink)

### ISSUE THREAD

**Issue by chgio** [guorbit/obc-model#51]
Existing diagrams to extend:
- [x] [PCBD] Root Physical Component Breakdown
- [x] [PAB] Root Physical Architecture
- [x] [PFBD] Root Physical Function Breakdown

New diagrams to create:
- [x] [CII] Root Internal Interfaces
- [x] [ES] Communications TX Scenario
- [x] (Optional) [PAB] Physical Architecture View of Communications TX
- [x] (Optional) [PDFB] Functional Dataflow View of Communications TX

**Comment by chgio** [comment]
[FlexTrak mock diagrams (LucidSpark)](https://lucid.app/lucidspark/8a6bf49f-6ec1-44ae-a846-2fe40b76b7bc/edit?invitationId=inv_66325ec1-2521-4d8d-928b-23baaa65d695)

**Comment by xszymonzur** [comment]
Additionally:
Add:

- [ ] [PFCD] Transciever Downlink

Edit (for why, see 82344d3):

- [ ] [PAB] Physical Architecture View of Telecommands
- [ ] [PAB] Physical Architecture View of Mode Changes
- [ ] [PAB] Physical Architecture View of Mission Activities
- [ ] [PFCD] Physical Functional Chain Description of Telemetry Retrieval (most notably)

btw after reading https://github.com/daveake/flexavr/blob/master/lora.ino I don't believe just sending the SSDV CMD (in FlexTrack's current state ofc) as proposed in the mock diagram in would do the trick :)

**Comment by chgio** [comment]
> don't believe just sending the SSDV CMD [...] would do the trick

can you please elaborate? :)

**Comment by xszymonzur** [comment]
Sure, [here](https://github.com/daveake/flexavr/blob/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6/lora.ino#L613-L624): ` if (++ImageCount > (GPS.Altitude > Settings.High ? Settings.HighImageCount : Settings.LowImageCount))
    {
      ImageCount = 0;
    }
    else if (SSDVBufferLength < 256)
    {
      ImageCount = 0;
    }` , and `if (ImageCount == 0) //send telemetry, otherwise send SSDV;` this means SSDV is send only when the buffer is full (correct me if I'm wrong here, it's late 😴) which in turn means there is a possibility the telemetry wouldn't be send right after the command (if it's too small) or, more likely, be [fractured](https://github.com/daveake/flexavr/blob/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6/lora.ino#L639). I'm assuming different telemetry retrievals and TC reports will have different sizes, so this approach might not be ideal (we could artificially "fill" up missing bytes to the full packet size but that seems wasteful).

Generally, to my limited understanding, there are two ways in which the out-of-the-box FlexTrack board sends data:

- telemetry - it is being sent continuously without the need of any external commands being issued to the board by the Pi (or the OBC in our case); it is the author's "intended" way of sending the telemetry, it is what the [recommended app](https://play.google.com/store/apps/details?id=com.daveakerman.HABExplora&hl=en) will display and the author's [firmware](https://github.com/daveake/flexavr/tree/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6) already provides the code to send some useful data with it. There is a possibility to use up to 6 ([source code says 4?](https://github.com/daveake/flextrak/blob/ef1dcf32c51cb49e80e621b5fc93116d1696cd8f/tracker.py#L53-L54) 🙃) Programmable Fields; this is the "intended" way of sending the additional telemetry. In the [Pi software](https://github.com/daveake/flextrak/tree/ef1dcf32c51cb49e80e621b5fc93116d1696cd8f) it is achieved by the [AddField(...)](https://github.com/daveake/flextrak/blob/ef1dcf32c51cb49e80e621b5fc93116d1696cd8f/flextrak.py#L101-L103) (it sends the ~F* command to the board), in the FlexTrack firmware they are stored in the [GPS.ExtraFields[...]](https://github.com/daveake/flexavr/blob/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6/flexavr.ino#L734-L738), a [TGPS struct](https://github.com/daveake/flexavr/blob/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6/flexavr.ino#L89-L112) (might seem rather peculiar but makes sense considering it was added later). Also, telemetry already has the [CRC](https://github.com/daveake/flexavr/blob/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6/misc.ino#L130-L148) attached to it for error detection. The [table](https://github.com/daveake/HAB-Documentation/blob/main/FlexTrak%20Manual.pdf) of available fields:
![image](https://github.com/guorbit/obc-model/assets/116189855/523b3eec-7d6a-4557-9dbe-150624093e24)
- SSDV (Slow Scan Digital Video?) - it is being sent in packets of [255 bytes](https://github.com/daveake/flexavr/blob/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6/lora.ino#L639) when the contents of the buffer exceed (or is equal to) 255 bytes; the commands `~SP` and `~SB` both append data to the buffer stored on the board. It is the author's "intended" way of sending images. The Pi software sends the SP command using [SendPacket](https://github.com/daveake/flextrak/blob/ef1dcf32c51cb49e80e621b5fc93116d1696cd8f/avr.py#L42-L51), which is called only in one [place](https://github.com/daveake/flextrak/blob/ef1dcf32c51cb49e80e621b5fc93116d1696cd8f/flextrak.py#L358-L362), taking the data from the camera as a parameter. The SB doesn't seem to be called at all. **It does, nevertheless, allow for transmission of arbitrary data.** The command is processed in [ProcessSSDVCommand(...)](https://github.com/daveake/flexavr/blob/59cb0b7ee0ed14fa4dc5c711cde09185f1dbeca6/flexavr.ino#L639-L684). I didn't find anything similar to the CRC attached to the packet, but maybe I have missed it.

Let me know if any of this makes sense and what doesn't. Of course we have the access to the source code of both the OBC and FlexTrack so we can change everything to our will (especially the OBC part, as we'll have to make that from scratch), and don't have to obey the "intended" parts but I'm concerned about the receiving end. We haven't discussed how we intend to receive the data at all, but those are my two cents. 😅

**Comment by chgio** [comment]
closing for abandonment of the FlexTrak in favour of an in-house-developed comms module based on the [STM32WL55JC Nucleo Devkit](https://www.st.com/en/evaluation-tools/nucleo-wl55jc.html).
thank you very much @xszymonzur for all your great work, keeping it for docs.
