### ISSUE TITLE
System Analysis: OBC Watchdog Disconnect

### ISSUE THREAD

**Issue by chgio** [guorbit/obc-model#7]
Existing diagrams to extend:
- [ ] [MCB] System Capabilities
- [ ] [CSA] System Actors
- [ ] [SFBD] Root System Function Breakdown
- [ ] [SAB] System Architecture

New diagrams to create:
- [ ] [ES] OBC Watchdog Disconnect Scenario:
  - own connection failure (heartbeat line open)
  - no effects of failure on hardware watchdog timer
- [ ] (Optional) [SDFB] Functional Dataflow View of OBC Watchdog Disconnect
- [ ] (Optional) [SAB] System Architecture View of OBC Watchdog Disconnect

Next steps:
when closing this issue, make a new issue out of the checkbox below:

- [ ] Logical Architecture: OBC Watchdog Disconnect

**Comment by xszymonzur** [comment]
This scenario is unlikely to happen and so the resolution of such a case will most likely be omitted altogether.
